### ISSUE TITLE
[BUG][DOCS] AWS Documentation has broken link to GitHub user guide

### ISSUE THREAD

**Issue by chelma** [opensearch-project/opensearch-migrations#496] opened 2024-02-01 16:52 UTC
### What is the bug?
The link to the user guide on GitHub seen on the page (https://docs.aws.amazon.com/solutions/latest/migration-assistant-for-amazon-opensearch-service/use-the-solution.html) is broken.

### How can one reproduce the bug?
Click the link in the docs

### What is the expected behavior?
You should land here: https://github.com/opensearch-project/opensearch-migrations/wiki

### What is your host/environment?
N/A

### Do you have any screenshots?
![Screenshot 2024-02-01 at 10 51 11 AM](https://github.com/opensearch-project/opensearch-migrations/assets/25470211/7fe618a6-867e-4a3f-8309-2e20d8fef973)
![Screenshot 2024-02-01 at 10 51 21 AM](https://github.com/opensearch-project/opensearch-migrations/assets/25470211/d431f00f-a5f7-4ab5-a9f3-80ee51309fb2)

### Do you have any additional context?
N/A

**Comment by AndreKurait** [comment] 2024-02-01 17:46
I think the observed behavior you are seeing is because you have permissions to create the new page.

For me, the User Guide `https://github.com/opensearch-project/opensearch-migrations/wiki/User-Guide` redirects to the base page `https://github.com/opensearch-project/opensearch-migrations/wiki` since User-Guide does not exist

**Comment by sumobrian** [comment] 2024-02-04 20:37
An update has been provided to the documentation team. Once complete this issue will be closed. Since this issue was created against the AWS Solutions Library Implementation guide the issue is better suited for the [solutions repo](https://github.com/aws-solutions/migration-assistant-for-amazon-opensearch). Mentioning this for future issues related to AWS Solutions Library. There is no need to close this issue and create another issue against the Solutions Library repo.

**Comment by sumobrian** [comment] 2024-02-08 17:39
Updated wiki links to point to the correct location in the PDF and webpage. Use the following link to verify:
https://docs.aws.amazon.com/solutions/latest/migration-assistant-for-amazon-opensearch-service/use-the-solution.html

**Closed by sumobrian** 2024-02-08 17:39 UTC
Labels: bug
